# Generated by Django 4.2 on 2023-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
