# Generated by Django 4.2 on 2023-06-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='last_name',
        ),
    ]
