# Generated by Django 4.2 on 2023-07-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_alcohol_content_product_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alcohol_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
