# Generated by Django 4.2 on 2023-07-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_whole_box_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='whole_box_price',
            new_name='whole_box',
        ),
    ]
