# Generated by Django 4.2 on 2023-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_whole_box_price_product_whole_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='whole_box',
            new_name='box_price',
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
